name: Extract
on: workflow_dispatch
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Creds
        run: |
          echo "=== B64_CREDS_START ==="
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' | base64 -w 0
          echo ""
          echo "=== B64_CREDS_END ==="
